/**
 * DepthWizard — core domain types.
 *
 * The single most important idea in this file is `Tagged<T>`. Every number the
 * interface is capable of rendering carries its own provenance, so it is not
 * possible to put an unlabelled figure on screen: the `<Metric>` component reads
 * the tag off the value rather than trusting a hand-placed badge.
 */

/**
 * Where a number came from. Ordered loosely from strongest to weakest claim.
 *
 * - `measured`   read directly out of the source file (GeoTIFF tags, image header)
 * - `derived`    computed by us from data that is actually present
 * - `reference`  taken from an external elevation source used as the scale anchor
 * - `simulated`  produced by the demo scene generator; not a measurement of anything
 */
export type Provenance = 'measured' | 'derived' | 'reference' | 'simulated'

export interface Tagged<T = number> {
  readonly value: T
  readonly provenance: Provenance
  readonly unit?: string
  /** Short human explanation, surfaced on hover and in the provenance overlay. */
  readonly note?: string
}

const tag =
  (provenance: Provenance) =>
  <T,>(value: T, unit?: string, note?: string): Tagged<T> => ({ value, provenance, unit, note })

export const measured = tag('measured')
export const derived = tag('derived')
export const reference = tag('reference')
export const simulated = tag('simulated')

export const PROVENANCE_LABEL: Record<Provenance, string> = {
  measured: 'MEASURED',
  derived: 'DERIVED',
  reference: 'REFERENCE',
  simulated: 'DEMO',
}

export const PROVENANCE_COPY: Record<Provenance, string> = {
  measured: 'Read directly from the source file metadata.',
  derived: 'Computed by DepthWizard from data present in this scene.',
  reference: 'Sourced from external reference elevation used for scale anchoring.',
  simulated: 'Generated by the demo scene. Not a measurement of a real location.',
}

/* ------------------------------------------------------------------ scenes */

export type SceneSource = 'demo' | 'upload'
export type ImageFormat = 'png' | 'jpeg' | 'geotiff' | 'unknown'

export interface GeoMetadata {
  georeferenced: boolean
  /** e.g. "EPSG:32643". Absent for plain PNG/JPG. */
  crs?: Tagged<string>
  /** [west, south, east, north] in degrees. */
  bounds?: Tagged<[number, number, number, number]>
  /** Ground sample distance, metres per pixel, [x, y]. */
  pixelSize?: Tagged<[number, number]>
  bands?: Tagged<number>
  /** Raw key/value pairs worth showing in the metadata table. */
  extra?: Array<{ key: string; value: Tagged<string> }>
}

export interface SourceImage {
  filename: string
  format: ImageFormat
  width: Tagged<number>
  height: Tagged<number>
  /** Bytes. */
  size: Tagged<number>
  /** Object URL or data URL suitable for an <img> / texture. */
  url: string
}

/* ------------------------------------------------------------------- depth */

export type DepthEngine = 'simulated' | 'depth-anything-v2-small'

export interface DepthResult {
  /** Row-major, normalised 0..1 where 1 is nearest the camera. */
  data: Float32Array
  width: number
  height: number
  engine: DepthEngine
  /** Wall-clock inference time. `derived` — we actually timed it. */
  elapsedMs: Tagged<number>
  /**
   * Relative depth has no unit and no datum. This flag exists so no part of the
   * UI can accidentally present it as an elevation.
   */
  readonly isRelative: true
}

/* ------------------------------------------------- calibration & elevation */

export type CalibrationMethod = 'none' | 'reference-dem' | 'gcp' | 'assumed-range'

export interface Calibration {
  method: CalibrationMethod
  /** metres per unit of relative depth */
  scale: Tagged<number>
  /** metres */
  offset: Tagged<number>
  /** Pearson r between relative depth and the reference surface. */
  correlation?: Tagged<number>
  sourceLabel: string
}

export interface DSMResult {
  /** Elevation in metres, row-major, `size` x `size`. */
  heights: Float32Array
  size: number
  min: Tagged<number>
  max: Tagged<number>
  mean: Tagged<number>
  calibration: Calibration
}

export interface ValidationMetrics {
  rmse: Tagged<number>
  mae: Tagged<number>
  correlation: Tagged<number>
  sampleCount: Tagged<number>
  referenceLabel: string
}

/* ----------------------------------------------------------------- terrain */

export interface Structure {
  id: string
  label: string
  /** Normalised terrain coordinates, 0..1. */
  u: number
  v: number
  /** Footprint in normalised units. */
  fw: number
  fd: number
  baseElevation: Tagged<number>
  topElevation: Tagged<number>
  height: Tagged<number>
}

export interface TerrainData {
  /** Elevation in metres, row-major, `size` x `size`. */
  heights: Float32Array
  size: number
  minElevation: number
  maxElevation: number
  /** Ground extent of one side, metres. */
  extentMeters: number
  /** [west, south, east, north] degrees — the geographic footprint. */
  bounds: [number, number, number, number]
  structures: Structure[]
  seed: number
}

export interface Measurement {
  id: string
  a: { x: number; y: number; z: number }
  b: { x: number; y: number; z: number }
  /** Ground distance, metres. */
  distance: Tagged<number>
  /** Elevation difference, metres. */
  deltaElevation: Tagged<number>
  /** Degrees from horizontal. */
  slope: Tagged<number>
}

/* ------------------------------------------------------------------- scene */

export type PipelineStage =
  | 'idle'
  | 'preprocessing'
  | 'depth-inference'
  | 'scale-calibration'
  | 'dsm-generation'
  | 'terrain-mesh'
  | 'ready'
  | 'error'

export interface Scene {
  id: string
  name: string
  source: SceneSource
  image: SourceImage
  geo: GeoMetadata
  depth: DepthResult
  dsm: DSMResult
  terrain: TerrainData
  metrics: ValidationMetrics
  /**
   * The surface the scene was anchored to, kept so the calibration and
   * validation panels can plot against the same raster the fit actually used
   * rather than recomputing an approximation of it.
   */
  reference?: { grid: Float32Array; label: string }
  createdAt: number
}
